# Generated by Django 5.0.4 on 2024-05-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buy_currency',
            field=models.CharField(default='USD', max_length=10),
            preserve_default=False,
        ),
    ]
