# Generated by Django 5.0.4 on 2024-05-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0002_payment_buy_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='table',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
    ]
