# Generated by Django 5.0.4 on 2024-05-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0003_payment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='table',
        ),
    ]
