# Generated by Django 5.0.4 on 2024-05-11 14:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0004_remove_payment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extOrderId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
