# Generated by Django 5.0.4 on 2024-05-11 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0005_payment_extorderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='extOrderId',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
