# Generated by Django 5.0.4 on 2024-05-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0006_alter_payment_extorderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='extOrderId',
        ),
    ]
