# Generated by Django 5.0.4 on 2024-05-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypaymentapp', '0007_remove_payment_extorderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
